# Generated by Django 2.2.9 on 2020-10-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201010_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='course_code',
            field=models.ForeignKey(default='Cours', on_delete=django.db.models.deletion.CASCADE, to='book.Course'),
        ),
    ]
