# Generated by Django 2.2.9 on 2020-10-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.CharField(max_length=200)),
                ('category_created_at', models.DateTimeField(auto_now=True)),
                ('category_short_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=200)),
                ('course_created_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(help_text='eg. PHY1001', max_length=200)),
                ('category_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.Category')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('video_content_description', models.TextField()),
                ('video_file', models.FileField(default='null', upload_to='videos/uploads/')),
                ('course_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='video.Course')),
            ],
            options={
                'verbose_name_plural': 'VideoTutorials',
            },
        ),
    ]
